server:
  port: 8082
feign:
  okhttp:
    enabled: true
#   以下是对共享配置的填充，但是还需要拉取这些配置从nacos到本地（在这里，先完成springcloud的上下文初始化，接着完成springboot得到上下文初始化）
#   但是nacos的地址时配置在application,yaml中的，无法找到nacos地址，因此需要起步的配置文件的读取bootstrap.yaml文件，基于nacosconfig来完成微服务的本地配置
#   引入依赖，添加配置
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城接口文档"
    package: com.hmall.cart.controller